### ISSUE TITLE
Break on import on unsupported Python versions

### ISSUE THREAD

**Issue by hynek** [hynek/attrs#121]
It seems like people are using attrs on unsupported Python versions(like…*gulp* 2.6) until they hit an incompatible code path and get a subtle breakage.

We should fail on `import attr` right away.

**Comment by hynek** [comment]
Heh we actually do already:

```
Python 2.6.9 (unknown, Sep 29 2016, 12:47:52)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import attr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hynek/.virtualenvs/tmp-bf7c0682227d576f/lib/python2.6/site-packages/attr/__init__.py", line 5, in <module>
    from ._funcs import (
  File "/Users/hynek/.virtualenvs/tmp-bf7c0682227d576f/lib/python2.6/site-packages/attr/_funcs.py", line 6, in <module>
    from ._make import NOTHING, fields, _obj_setattr
  File "/Users/hynek/.virtualenvs/tmp-bf7c0682227d576f/lib/python2.6/site-packages/attr/_make.py", line 829, in <module>
    class Factory(object):
  File "/Users/hynek/.virtualenvs/tmp-bf7c0682227d576f/lib/python2.6/site-packages/attr/_make.py", line 288, in wrap
    _transform_attrs(cls, these)
  File "/Users/hynek/.virtualenvs/tmp-bf7c0682227d576f/lib/python2.6/site-packages/attr/_make.py", line 173, in _transform_attrs
    AttrsClass = _make_attr_tuple_class(cls.__name__, attr_names)
  File "/Users/hynek/.virtualenvs/tmp-bf7c0682227d576f/lib/python2.6/site-packages/attr/_make.py", line 126, in _make_attr_tuple_class
    attr_class_name = "{}Attributes".format(cls_name)
ValueError: zero length field name in format
```
