### ISSUE TITLE
attr.s(frozen=True) breaks writeable properties

### ISSUE THREAD

**Issue by exarkun** [hynek/attrs#144]
```
(txkube) exarkun@baryon:~/Work/LeastAuthority/txkube$ cat brokenattrs.py
import attr

@attr.s(frozen=True)
class X(object):
    y = attr.ib()

    @property
    def z(self):
        return 3

    @z.setter
    def z(self, value):
        print("z=", value)

X(y=None).z = 10
(txkube) exarkun@baryon:~/Work/LeastAuthority/txkube$ python brokenattrs.py 
Traceback (most recent call last):
  File "brokenattrs.py", line 15, in <module>
    X(y=None).z = 10
  File "/home/exarkun/Environments/txkube/local/lib/python2.7/site-packages/attr/_make.py", line 201, in _frozen_setattrs
    raise FrozenInstanceError()
attr.exceptions.FrozenInstanceError
(txkube) exarkun@baryon:~/Work/LeastAuthority/txkube$ 
```

**Comment by hynek** [comment]
Heh we freeze the classes for good ATM.  There seems to be interest in a more…flexible freezing process (c.f. also #133).

**Comment by joeblackwaslike** [comment]
I opened an issue for with initial pull request for customizing __setattr__ and __delattr__ for frozen classes here: https://github.com/python-attrs/attrs/issues/378

**Comment by EikeScholz** [comment]
Hi @exarkun

I'm Eike, CTO @ Polygravity. We just moved into a lovely new office space and we need to fill it up with highly qualified people stat!
In a nutshell, Polygravity is a blockchain based decentralized transactions network, which enables secure real-time processing and notarization capable of operating at an unlimited scale. The system has military-grade security and unyielding privacy for its data. Also, the network doesn’t users to use cryptocurrencies in order to execute transactions.

I've come across your GitHub profile and quite liked your work. Your repositories look great and I like the stuff you are using. Quite a testament to your skills as a developer! We are currently looking for developers to fill up a few positions and we think you would make an excellent addition to our team.
If you want to read more about our venture, you can go to our website at https://polygravity.io

You can contact me at eike.scholz@polygravity.io

**Comment by cjw296** [comment]
hey @EikeScholz, you know you come across really really badly when you spam an issue tracker with some crappy job offer? Blockchain! Woo! "military-grade security", Wow! "_quite_ liked your work"? How flattering...

**Comment by maz808** [comment]
I'm having trouble understanding the solution to this. Is this still not supported or am I missing something? What I ultimately want to do is be able to set a single attribute of a class that has inherited a frozen status. Is this even possible?

**Comment by hynek** [comment]
you can always set any attribute using `object.__setattr__`. An example is in https://www.attrs.org/en/stable/init.html#post-init

**Comment by maz808** [comment]
> you can always set any attribute using `object.__setattr__`. An example is in https://www.attrs.org/en/stable/init.html#post-init

I have started doing that in a method for the frozen class, but I really would prefer this:
 `class_instance.attribute = value` 
over this: `class_instance.change_attribute(value)`  

I guess I should have mentioned that. I appreciate the response, but I'm still uncertain if what I want is even doable right now.

**Comment by hynek** [comment]
At this point, allowing for this would break a lot of contracts since _attrs_ makes assumptions based on the frozen-ness of a class (most notably, hashability) so I don't want to add features that surprisingly would undermine that.  We've added many features for pluggable control of setters, tho!
