### ISSUE TITLE
frozen class is made immutable before __attrs_post_init__ gets a turn

### ISSUE THREAD

**Issue by wsanchez** [hynek/attrs#147]
This code:

```python
from attr import attrib, attrs

@attrs(frozen=True)
class Foo(object):
    def __attrs_post_init__(self):
        self._thing = object()

Foo()
```

Raises `FrozenInstanceError`:

```console
wsanchez$ python /tmp/foo.py
Traceback (most recent call last):
  File "/tmp/foo.py", line 8, in <module>
    Foo()
  File "<attrs generated init 97d170e1550eee4afc0af065b78cda302a97674c>", line 3, in __init__
  File "/tmp/foo.py", line 6, in __attrs_post_init__
    self._thing = object()
  File "/.../attr/_make.py", line 201, in _frozen_setattrs
    raise FrozenInstanceError()
attr.exceptions.FrozenInstanceError
```

It would be nice if `__attrs_post_init__` can set attributes before the object is frozen.

**Comment by wsanchez** [comment]
Ref #111

**Comment by hynek** [comment]
I believe this is a dupe of #120.

The problem is as I explained there that the object never actually is unfrozen.  We just work around the frozen-ness.  Would any of the ideas in the other issue there suite you?

**Comment by wsanchez** [comment]
Yes that looks like a dup, thanks.
