### ISSUE TITLE
Support for multi-level inheritance

### ISSUE THREAD

**Issue by cournape** [hynek/attrs#24]
I was quite excited to see characteristic improved to use descriptors, but I was surprised by following behaviour:

``` python
from attr import attributes, attr
@attributes
class A(object):
    a = attr()
@attributes
class B(A):
    b = attr()
@attributes
class C(B):
    c = attr()
```

raises a syntax error:

```
Traceback (most recent call last):
  File "yo.py", line 15, in <module>
    class C(B):
  File "/home/davidc/.envs/jaguar-dev/local/lib/python2.7/site-packages/attr/_make.py", line 194, in attributes
    return wrap(maybe_cl)
  File "/home/davidc/.envs/jaguar-dev/local/lib/python2.7/site-packages/attr/_make.py", line 186, in wrap
    cl = _add_init(cl)
  File "/home/davidc/.envs/jaguar-dev/local/lib/python2.7/site-packages/attr/_make.py", line 340, in _add_init
    bytecode = compile(script, unique_filename, "exec")
  File "<attrs generated init 24e3b3b777d1b457ffb869223ee4a4b7665529ed>", line 1
SyntaxError: duplicate argument 'a' in function definition
```

So it looks like one level of inheritance works (`B` works as expected), but not multiple.

**Comment by hynek** [comment]
Congratulations, you found the first bug in attrs. :)

**Comment by hynek** [comment]
If you could verify your issue is fixed I’d roll 15.1.0.  Thanks!

**Comment by cournape** [comment]
Looks like it works ! Thanks for the prompt fix

**Comment by hynek** [comment]
(I have to correct myself: the first bug in a released version.  the first bug overall was found by @econchick in #5, mea culpa ;))
