### ISSUE TITLE
If an object has a property on it which triggers one of attrs' methods during set, and set is called during the constructor, bad things happen

### ISSUE THREAD

**Issue by ctoth** [hynek/attrs#47]
``` python
from attr import attr, attributes

@attributes(these = {
	'a': attr()
})
class Test(object):

	def __init__(self, *args, **kwargs):
		self._a = None
		super(Test, self).__init__(*args, **kwargs)

	def set_a(self, val):
		if val is not None:
			val.add(self)
		self._a = val

	def get_a(self):
		return self._a
	a = property(get_a, set_a)

>>> s=set()
>>> t=Test(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<attrs generated init 598ab62ad1f7da66a4de0a0e4c8e06f757331088>", line 3, in __init__
  File "test_attr.py", line 14, in set_a
    val.add(self)
  File "c:\python27\lib\site-packages\attr\_make.py", line 215, in hash_
    return hash(_attrs_to_tuple(self, attrs))
  File "c:\python27\lib\site-packages\attr\_make.py", line 201, in _attrs_to_tuple
    return tuple(getattr(obj, a.name) for a in attrs)
  File "c:\python27\lib\site-packages\attr\_make.py", line 201, in <genexpr>
    return tuple(getattr(obj, a.name) for a in attrs)
  File "test_attr.py", line 18, in get_a
    return self._a
AttributeError: 'Test' object has no attribute '_a'
```

**Comment by hynek** [comment]
A couple of things that jump into my eyes:

- if you want to write your own `__init__`, you have to use `attr(init=False)` otherwise attrs will try to attach its own `__init__`.
- you don’t actually want attrs to keep track of an `a` attribute for you but `_a`.  This seems to be the main confusion here.  There is an example for using properties that is pretty close to what you want in https://attrs.readthedocs.io/en/stable/examples.html (just look `Or if you want to use properties:`).

I’m closing this issue for now.  Feel free to re-open if I’ve missed something.
